// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN5JJzEi3ebRH_6DfFhToiu-ioDAebPnY',
    appId: '1:848608299624:web:e7d555b71d7f0fc13349dd',
    messagingSenderId: '848608299624',
    projectId: 'hackathon1-38c85',
    authDomain: 'hackathon1-38c85.firebaseapp.com',
    storageBucket: 'hackathon1-38c85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1auM8WRPQ2tFeA4FQgxqr3VJx6h682-E',
    appId: '1:848608299624:android:2c779429e339561b3349dd',
    messagingSenderId: '848608299624',
    projectId: 'hackathon1-38c85',
    storageBucket: 'hackathon1-38c85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgJN4uQYGRzFuKBcqT90Qo0cjRLYnyjc4',
    appId: '1:848608299624:ios:2aad9defa0d092d93349dd',
    messagingSenderId: '848608299624',
    projectId: 'hackathon1-38c85',
    storageBucket: 'hackathon1-38c85.appspot.com',
    iosClientId: '848608299624-418qhfmi8b5sbda31qmtepl56ed081os.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathon',
  );
}
